name: Build and Push Docker Image

# Trigger the workflow on pushes to the master branch and on pull requests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/linode-s3-notifier:${{ github.sha }} .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/linode-s3-notifier:${{ github.sha }}

      # Optionally, tag and push the image as 'latest'
      - name: Tag image as latest and push
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/linode-s3-notifier:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/linode-s3-notifier:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/linode-s3-notifier:latest
